language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: shareyourideas-node
  api_key:
    secure: owNsePisdR/2APJ2hpF5nicUPVHfQ7wPZODkHXrGCvvDii0SgLrjjXhk7DDeQkyOOvkS03MEigXkFcOQLtmHGfYqqTpRPPjQMJwDZ3m3b5ZafCEfLULSjVqItQLlm+zZShdWdvQXopsMJpwamwGBb81eByLfMz1geISDGGhAEZiY7Zh2RmiVbVgDnPIS1jggFxct4JuyIvZ9nx3dbtCiBRcmo/C76LFGWjZlz6zuu+T9MHemzZVjHOpzDTy/+AJb7TAYuJMBFXrXx4OpOLBh/XEXDBlXawWO/GPehJDE9ctfqeYxxQtVzVtCPbl9SevkajS3LrDZs8pA+USmhekA9ZRS08Ep10YDNlt/ogElGjw8SERZiqfmm0c4mFUfxsVRN+4B093p7O3wOJVrypF6Sj9Y6Y45x4RWnBpCHSz1iS/BUYRPwAOe0iomm8Uy3iz4F7KkcUkxHMkO9Nfk8PLscsyD94Chc+WpgjeVovZLy7sWYNoZ7kvYz9hmYjNzShGguZ77uKFd+ZkuDSiSnjBpEwP0ZAZq1q6Osfl0ToeYZNUvRJ9bM3CrTKD1sMcj3mvhz+85K5AUEk70+JsmZ5d0XEOmYkFp6LcBaneC2yFhlu9jQk0wwKsEPLeaE/XHMFTnJhZP413UiwZjDJDNdl0264c71CMf030YmqMysw5AZOs=
